### ISSUE TITLE
No longer functioning

### ISSUE THREAD

**Issue by gitmeED331** [duzda/deezer-enhanced#59]
OS: Arch Linux
App Version: 1.1.0

![Screenshot-area_24-10-21_2237-48](https://github.com/user-attachments/assets/b82e5681-09b2-49d9-979f-9c4ad374cbe0)

Not sure what is wrong, but Deezer Enhanced does not seem to be able to play anything anymore. 
My connection is good as I have no issues with anything else.
Nothing changed in my firewalls.
It worked fine yesterday.

What is pictured occurs with every song and has all day.

**Comment by duzda** [comment]
Thanks for reporting, will look into it, as it happens on my computer as well.

**Comment by duzda** [comment]
Chromium 122 is no longer compatible with Deezer, which means we have to migrate to another version :(. Going back sucks, but going up requires huge refactor and some libraries would need to be replaced.

**Comment by OuraN2O** [comment]
> Chromium 122 is no longer compatible with Deezer, which means we have to migrate to another version :(. Going back sucks, but going up requires huge refactor and some libraries would need to be replaced.

When do you think it would be usable again ? Don't mean to pressure you or anything just to have some expectation (or not)

**Comment by duzda** [comment]
> When do you think it would be usable again ? Don't mean to pressure you or anything just to have some expectation (or not)

I will take a deeper look on friday and weekend, I don't think it's realistic to get it done by a single weekend, two should suffice though, but it's really hard to guess.

**Comment by Gamer2097** [comment]
For me, it just started working again right now, not sure why, haven't done anything in particular either

**Comment by duzda** [comment]
> For me, it just started working again right now, not sure why, haven't done anything in particular either (i had the same issue as the one mentioned above)

Yeah, I wish all my problems could be solved this easily :grin: Probably can safely close as it got fixed by upstream, but keeping open for a little bit longer.

**Comment by OuraN2O** [comment]
Yeah it's currently working on my system too

**Comment by gitmeED331** [comment]
I confirm as well that it is working again. Wonder what the issue was.

**Comment by duzda** [comment]
Closing as hopefully this won't reappear anytime soon.

**Comment by gitmeED331** [comment]
Well, that may have been premature.

Today, the app will play but it is throwing a lot of errors making it so mpris is having trouble with it. This leads my bar unable to register it nor get info from it.

here is a error sample  (happening on both River and Hyprland):

```bash
(node:58557) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.onerror (/opt/deezer-enhanced/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (node:events:629:26)
    at Socket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
(Use `deezer-enhanced --trace-warnings ...` to show where the warning was created)
(node:58557) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:58557) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'write')
    at IPCTransport.send (/opt/deezer-enhanced/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:155:17)
    at /opt/deezer-enhanced/resources/app.asar/node_modules/discord-rpc/src/client.js:159:22
    at new Promise (<anonymous>)
    at RPCClient.request (/opt/deezer-enhanced/resources/app.asar/node_modules/discord-rpc/src/client.js:157:12)
    at RPCClient.setActivity (/opt/deezer-enhanced/resources/app.asar/node_modules/discord-rpc/src/client.js:518:17)
    at setDiscordActivity (/opt/deezer-enhanced/resources/app.asar/src/main/discord.ts:44:18)
    at IpcMainImpl.<anonymous> (/opt/deezer-enhanced/resources/app.asar/src/main/mpris.ts:119:9)
    at IpcMainImpl.emit (node:events:514:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78003)
    at WebContents.emit (node:events:514:28)
(node:58557) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:58557) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'write')
    at IPCTransport.send (/opt/deezer-enhanced/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:155:17)
    at /opt/deezer-enhanced/resources/app.asar/node_modules/discord-rpc/src/client.js:159:22
    at new Promise (<anonymous>)
    at RPCClient.request (/opt/deezer-enhanced/resources/app.asar/node_modules/discord-rpc/src/client.js:157:12)
    at RPCClient.setActivity (/opt/deezer-enhanced/resources/app.asar/node_modules/discord-rpc/src/client.js:518:17)
    at setDiscordActivity (/opt/deezer-enhanced/resources/app.asar/src/main/discord.ts:44:18)
    at IpcMainImpl.<anonymous> (/opt/deezer-enhanced/resources/app.asar/src/main/mpris.ts:119:9)
    at IpcMainImpl.emit (node:events:514:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78003)
    at WebContents.emit (node:events:514:28)
(node:58557) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:58557) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'write')
    at IPCTransport.send (/opt/deezer-enhanced/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:155:17)
    at /opt/deezer-enhanced/resources/app.asar/node_modules/discord-rpc/src/client.js:159:22
    at new Promise (<anonymous>)
    at RPCClient.request (/opt/deezer-enhanced/resources/app.asar/node_modules/discord-rpc/src/client.js:157:12)
    at RPCClient.setActivity (/opt/deezer-enhanced/resources/app.asar/node_modules/discord-rpc/src/client.js:518:17)
    at setDiscordActivity (/opt/deezer-enhanced/resources/app.asar/src/main/discord.ts:44:18)
    at IpcMainImpl.<anonymous> (/opt/deezer-enhanced/resources/app.asar/src/main/mpris.ts:119:9)
    at IpcMainImpl.emit (node:events:514:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78003)
    at WebContents.emit (node:events:514:28)
(node:58557) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
```

**Comment by duzda** [comment]
These errors are related to Discord Rich Presence (RPC), not mpris. In my head it makes sense that an error is thrown and logged when Deezer tries to set Discord RPC but is unable to (typically your Discord app is either not running or has RPC turned off). As to why mpris doesn't work in your case, who knows, I'd suggest you to try for example YouTube within your web browser to confirm that the basic `mpris` implementation is working.
